#!/usr/bin/env python3
"""Generate the template's starter art set: 16-colour tiles and the UI font.

Textures are 16x16 CI4 -- four bits per texel indexing a 16-entry RGBA5551
palette, so 160 bytes each.  That is small enough to sit in the RDP's 4 KB
TMEM with its palette and no tiling, which is why the engine's texture type is
this shape and not a general one.

The tiles below are a starting point, not a style: replace them.  Two things
about them are worth keeping when you do.

  * No single-pixel detail.  A nearest-sampled CI4 texture on a composite
    signal turns pixel noise into shimmer that reads as corruption.  Work in
    2x2 blocks or larger.
  * Four colours, not sixteen.  The palette has room for sixteen, but a tile
    that uses four reads as one material on a CRT; one that uses sixteen reads
    as mud.

For hand-drawn art instead of procedural tiles, draw a PNG atlas and import it
-- see docs/custom-textures.md.  The font is generated here too, and the engine
depends on its layout; see write_font.
"""

from pathlib import Path

ASSET_DIR = Path("assets")


def rgba5551(rgb):
    r, g, b = rgb[:3]
    alpha = rgb[3] if len(rgb) == 4 else 255
    return ((r >> 3) << 11) | ((g >> 3) << 6) | ((b >> 3) << 1) | (1 if alpha else 0)


def pack_nibbles(values):
    result = []
    for offset in range(0, len(values), 8):
        word = 0
        for value in values[offset:offset + 8]:
            word = (word << 4) | value
        result.append(word)
    return result


def mottled(x, y, salt):
    """A 2x2-pixel, low-frequency pattern that stays readable on a CRT."""
    return ((x // 2) * 3 + (y // 2) * 5 + ((x // 4) * (y // 4)) + salt) & 3


def tile(kind, x, y):
    """The texel index (0-15) at (x, y) of a 16x16 tile."""
    if kind == "crate":
        # A bordered panel: dark frame, banded interior, brighter corners.
        if x < 2 or x > 13 or y < 2 or y > 13:
            return 0
        if x < 3 or x > 12 or y < 3 or y > 12:
            return 3
        return 1 + ((x // 4 + y // 4) & 1)
    if kind == "ground":
        return 1 + (mottled(x, y, 1) >> 1)
    if kind == "stone":
        # Offset 8x4 blocks with a single dark mortar line between them.
        shifted_x = (x + ((y // 4) & 1) * 3) & 15
        if y % 4 == 0 or shifted_x % 8 == 0:
            return 0
        return 1 + ((shifted_x // 4 + y // 4) & 1)
    if kind == "checker":
        # Deliberately plain: the tile to reach for when you want to see where
        # a surface's texture coordinates actually go.
        return 3 if ((x // 4) + (y // 4)) & 1 else 0
    raise ValueError(f"unknown tile kind: {kind}")


# Four colours per tile, darkest first.  A fifth entry would be legal -- the
# palette holds sixteen -- but see the note at the top of the file.
PALETTES = {
    "crate": [(72, 43, 22), (137, 87, 43), (174, 115, 62), (203, 152, 92)],
    "ground": [(58, 42, 28), (92, 70, 44), (120, 95, 60), (146, 118, 78)],
    "stone": [(57, 62, 64), (85, 91, 93), (108, 114, 115), (132, 137, 137)],
    "checker": [(28, 30, 38), (60, 64, 78), (96, 102, 120), (188, 194, 210)],
}


def write_textures():
    chunks = ["// Generated by generate_assets.py -- do not edit.\n",
              "// The Texture type itself lives in engine/include/gfx.h.\n",
              '#include "gfx.h"\n']
    for name, palette in PALETTES.items():
        indices = [tile(name, x, y) for y in range(16) for x in range(16)]
        words = pack_nibbles(indices)
        palette_words = [rgba5551(colour) for colour in palette] + [0] * (16 - len(palette))
        index_text = ", ".join(f"0x{word:08X}" for word in words)
        palette_text = ", ".join(f"0x{word:04X}" for word in palette_words)
        chunks.append(f"\nTexture {name}_texture = {{ {{ {index_text} }}, {{ {palette_text} }} }};\n")
    (ASSET_DIR / "texture_data.h").write_text("".join(chunks))


# The UI font: 5x7 glyphs on 8x8 cells, ASCII from space up, laid out sixteen
# to a row in a 128x64 I4 atlas.  engine/src/text.c indexes it directly, so the
# cell size and the two blank rows at the top are part of the contract -- the
# blank rows are there for a game that wants to add symbols of its own without
# moving the printable set.
#
# There is no lowercase: a mixed-case string reads wrong on the console because
# 'i' lands on the colon.  Capitalise UI text, or draw the missing glyphs here.
GLYPHS = {
    "A": ("01110", "10001", "10001", "11111", "10001", "10001", "10001"),
    "B": ("11110", "10001", "10001", "11110", "10001", "10001", "11110"),
    "C": ("01111", "10000", "10000", "10000", "10000", "10000", "01111"),
    "D": ("11110", "10001", "10001", "10001", "10001", "10001", "11110"),
    "E": ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    "F": ("11111", "10000", "10000", "11110", "10000", "10000", "10000"),
    "G": ("01111", "10000", "10000", "10111", "10001", "10001", "01111"),
    "H": ("10001", "10001", "10001", "11111", "10001", "10001", "10001"),
    "I": ("11111", "00100", "00100", "00100", "00100", "00100", "11111"),
    "J": ("00111", "00010", "00010", "00010", "10010", "10010", "01100"),
    "K": ("10001", "10010", "10100", "11000", "10100", "10010", "10001"),
    "L": ("10000", "10000", "10000", "10000", "10000", "10000", "11111"),
    "M": ("10001", "11011", "10101", "10101", "10001", "10001", "10001"),
    "N": ("10001", "11001", "10101", "10011", "10001", "10001", "10001"),
    "O": ("01110", "10001", "10001", "10001", "10001", "10001", "01110"),
    "P": ("11110", "10001", "10001", "11110", "10000", "10000", "10000"),
    "Q": ("01110", "10001", "10001", "10001", "10101", "10010", "01101"),
    "R": ("11110", "10001", "10001", "11110", "10100", "10010", "10001"),
    "S": ("01111", "10000", "10000", "01110", "00001", "00001", "11110"),
    "T": ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
    "U": ("10001", "10001", "10001", "10001", "10001", "10001", "01110"),
    "V": ("10001", "10001", "10001", "10001", "10001", "01010", "00100"),
    "W": ("10001", "10001", "10001", "10101", "10101", "10101", "01010"),
    "X": ("10001", "10001", "01010", "00100", "01010", "10001", "10001"),
    "Y": ("10001", "10001", "01010", "00100", "00100", "00100", "00100"),
    "Z": ("11111", "00001", "00010", "00100", "01000", "10000", "11111"),
    "0": ("01110", "10001", "10011", "10101", "11001", "10001", "01110"),
    "1": ("00100", "01100", "00100", "00100", "00100", "00100", "01110"),
    "2": ("01110", "10001", "00001", "00010", "00100", "01000", "11111"),
    "3": ("11110", "00001", "00001", "01110", "00001", "00001", "11110"),
    "4": ("00010", "00110", "01010", "10010", "11111", "00010", "00010"),
    "5": ("11111", "10000", "10000", "11110", "00001", "00001", "11110"),
    "6": ("01110", "10000", "10000", "11110", "10001", "10001", "01110"),
    "7": ("11111", "00001", "00010", "00100", "01000", "01000", "01000"),
    "8": ("01110", "10001", "10001", "01110", "10001", "10001", "01110"),
    "9": ("01110", "10001", "10001", "01111", "00001", "00001", "01110"),
    ":": ("00000", "00100", "00100", "00000", "00100", "00100", "00000"),
    ".": ("00000", "00000", "00000", "00000", "00000", "00110", "00110"),
    ">": ("10000", "01000", "00100", "00010", "00100", "01000", "10000"),
    "<": ("00001", "00010", "00100", "01000", "00100", "00010", "00001"),
    "-": ("00000", "00000", "00000", "11111", "00000", "00000", "00000"),
    # Sentence punctuation. The atlas held capitals, digits and four symbols,
    # so any UI text with an exclamation, a comma, an apostrophe or a slash
    # came out with a seven-pixel hole where the mark should be. Battle and
    # dialogue text needs all four; every other screen is free to keep
    # avoiding them.
    "!": ("00100", "00100", "00100", "00100", "00100", "00000", "00100"),
    ",": ("00000", "00000", "00000", "00000", "00110", "00110", "01100"),
    "'": ("00100", "00100", "00100", "00000", "00000", "00000", "00000"),
    "/": ("00001", "00010", "00010", "00100", "01000", "01000", "10000"),
    "?": ("01110", "10001", "00001", "00010", "00100", "00000", "00100"),
}


def write_font():
    pixels = [[0 for _ in range(128)] for _ in range(64)]
    for codepoint in range(32, 128):
        glyph = GLYPHS.get(chr(codepoint).upper(), ())
        cell_x = (codepoint - 32) % 16
        cell_y = 16 + ((codepoint - 32) // 16) * 8
        for y, row in enumerate(glyph):
            for x, bit in enumerate(row):
                if bit == "1":
                    pixels[cell_y + y][cell_x * 8 + x + 1] = 15
    packed = pack_nibbles([pixel for row in pixels for pixel in row])
    body = ",\n  ".join(f"0x{word:08X}" for word in packed)
    (ASSET_DIR / "font.h").write_text("// Generated by generate_assets.py -- do not edit.\n#include <nusys.h>\n\nu32 font_texture[] __attribute__((aligned(8))) = {\n  " + body + "\n};\n")



if __name__ == "__main__":
    ASSET_DIR.mkdir(exist_ok=True)
    write_textures()
    write_font()
