/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef MUSIC_GAME_VADPCM_H
#define MUSIC_GAME_VADPCM_H

#define MUSIC_GAME_VADPCM_SAMPLE_RATE 12000
#define MUSIC_GAME_VADPCM_SAMPLE_COUNT 1293600
#define MUSIC_GAME_VADPCM_DATA_BYTES 727650
#define MUSIC_GAME_VADPCM_BOOK_ORDER 2
#define MUSIC_GAME_VADPCM_BOOK_PREDICTORS 4
#define MUSIC_GAME_VADPCM_BOOK_VALUES { \
   -1931,  -3720,  -5345,  -6789,  -8038,  -9082,  -9917, -10540, \
    3945,   5669,   7200,   8525,   9633,  10518,  11179,  11618, \
   -1923,  -3290,  -3824,  -3454,  -2320,   -726,    936,   2283, \
    3504,   4073,   3679,   2471,    773,   -996,  -2431,  -3224, \
    -953,  -1183,  -1025,   -723,   -420,   -185,    -35,     43, \
    2543,   2204,   1553,    903,    399,     75,    -93,   -150, \
   -1965,  -3672,  -4977,  -5777,  -6021,  -5709,  -4892,  -3664, \
    3827,   5187,   6021,   6276,   5950,   5098,   3818,   2244, \
}
#define MUSIC_GAME_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* MUSIC_GAME_VADPCM_H */
