#ifndef ENGINE_AUDIO_H
#define ENGINE_AUDIO_H

#include <nusys.h>

/*
 * Sound, through libultra's audio library.
 *
 * Audio is a build variant rather than a runtime switch (`make audio`): it
 * costs a second thread, a 70 KiB heap under the framebuffers and the ROM
 * space for the samples, and a game that does not want it should not pay for
 * any of that.  Everything here compiles to nothing without ENABLE_AUDIO, so
 * game code calls it unconditionally and never needs an #ifdef of its own.
 *
 * Music is streamed VADPCM from ROM; effects are short PCM held in memory.
 * The asset pipeline is in the Makefile -- `make music` and `make sfx`.  See
 * docs/building.md.
 */

/*
 * The slots.  These are positions in the ROM layout (see spec.audio), not a
 * fixed vocabulary: the four effects are procedurally generated by
 * tools/generate_sfx.py and named for the sound they make rather than for what
 * a game uses them for, so a menu confirm and a coin pickup can both be
 * SOUND_CHIME.
 *
 * Adding a fifth means a segment in spec.audio, an extern and a prepareEffect
 * call in engine/src/audio.c, and an entry in the generator.  Adding music is
 * the same three places.
 */
#define MUSIC_TRACK_COUNT 2
#define MUSIC_TITLE 0
#define MUSIC_GAME 1

#define SOUND_EFFECT_COUNT 4
#define SOUND_CHIME 0    /* a short rising tone -- confirm, pickup */
#define SOUND_THUMP 1    /* a low soft hit -- landing, a heavy step */
#define SOUND_IMPACT 2   /* three noisy taps -- something breaking */
#define SOUND_CLICK 3    /* a woody knock -- placing, a cursor move */

/*
 * Loudness, as steps rather than a raw amplitude: an options screen draws these
 * as a row of pips and the player counts them, so the scale has to be short
 * enough to count and the endpoints have to mean something.  Step 0 is
 * silence, the last step is the level the game was mixed at.
 *
 * Declared outside ENABLE_AUDIO because the screen that draws the pips is
 * built either way; only the calls that reach the audio library are compiled
 * out.
 */
#define AUDIO_VOLUME_STEPS 5
#define AUDIO_VOLUME_DEFAULT (AUDIO_VOLUME_STEPS - 1)

#ifdef ENABLE_AUDIO

void initAudio(void);
/* Once per graphics callback, after game logic. */
void updateAudio(void);

void playSound(u8 effect);
/* Start a track, or MUSIC_NONE for silence.  Starting the track already
   playing is a no-op rather than a restart. */
#define MUSIC_NONE 255
void playMusic(u8 track);
u8 currentMusic(void);

/*
 * Volume takes effect on the voice already playing rather than restarting it,
 * which is why silence is step zero here instead of a stop: stopping
 * deallocates the voice, and turning the music back up would start the song
 * again from its first bar.
 */
void setMusicVolume(u8 step);
void setSoundVolume(u8 step);
u8 musicVolume(void);
u8 soundVolume(void);

/*
 * Peak KiB taken from the audio heap, for the diagnostics overlay.
 *
 * An undersized audio heap fails only on hardware and only as silence or
 * corruption -- no emulator reproduces it.  Anything that changes the voice
 * count, the DMA buffers or the command list moves the ceiling, so re-read
 * this on a console rather than trusting the configured size to hold.
 */
u32 audioHeapPeakKiB(void);

#else

/* A build with no audio still draws the rows, so they answer honestly: the
   volume is zero and setting it does nothing. */
#define MUSIC_NONE 255
#define initAudio() ((void) 0)
#define updateAudio() ((void) 0)
#define playSound(effect) ((void) (effect))
#define playMusic(track) ((void) (track))
#define currentMusic() ((u8) MUSIC_NONE)
#define setMusicVolume(step) ((void) (step))
#define setSoundVolume(step) ((void) (step))
#define musicVolume() ((u8) 0)
#define soundVolume() ((u8) 0)
#define audioHeapPeakKiB() ((u32) 0)

#endif /* ENABLE_AUDIO */

#endif /* ENGINE_AUDIO_H */
