#!/usr/bin/env python3
"""Generate the game's short, original gameplay sound effects.

The N64 sound player consumes signed 16-bit PCM in big-endian byte order.
This tool also writes ordinary WAV preview files so the effects can be
auditioned without building a ROM.  It intentionally uses only the Python
standard library, keeping the audio build reproducible in the SDK container.
"""

import math
import struct
import wave
from pathlib import Path


SAMPLE_RATE = 22050


def noise(seed: int) -> float:
    """Return deterministic, inexpensive white noise in the -1..1 range."""
    seed = (seed * 1103515245 + 12345) & 0x7FFFFFFF
    return (seed / 1073741823.5) - 1.0


def envelope(t: float, decay: float) -> float:
    return math.exp(-t * decay)


def pickup(t: float, index: int) -> float:
    """A bright two-note chime: quick, friendly, and clearly collectible."""
    if t < 0.075:
        phase = 2.0 * math.pi * 1318.51 * t
        level = envelope(t, 18.0)
    else:
        phase = 2.0 * math.pi * 1760.0 * (t - 0.075)
        level = 0.82 * envelope(t - 0.075, 20.0)
    tone = math.sin(phase) + 0.23 * math.sin(phase * 2.0)
    sparkle = noise(index) * 0.025 * envelope(t, 42.0)
    return level * tone * 0.58 + sparkle


def punch(t: float, index: int) -> float:
    """A compact, low thud with a dry attack for hand/tool contact."""
    sweep = 175.0 - min(t * 850.0, 88.0)
    body = math.sin(2.0 * math.pi * sweep * t) * envelope(t, 25.0)
    crack = noise(index + 97) * envelope(t, 52.0)
    return body * 0.56 + crack * 0.26


def block_break(t: float, index: int) -> float:
    """Three tiny noisy impacts, giving a cube a chunky break character."""
    result = 0.0
    for offset, strength in ((0.0, 1.0), (0.045, 0.62), (0.096, 0.38)):
        local = t - offset
        if local >= 0.0:
            thump = math.sin(2.0 * math.pi * 145.0 * local)
            result += strength * envelope(local, 35.0) * (thump * 0.38 + noise(index + int(offset * 1000)) * 0.33)
    return result


def place(t: float, index: int) -> float:
    """A woody click with a short, warm knock for placed blocks."""
    knock = math.sin(2.0 * math.pi * 205.0 * t) * envelope(t, 34.0)
    click = noise(index + 271) * envelope(t, 75.0)
    return knock * 0.52 + click * 0.18


EFFECTS = (
    ("chime", 0.18, pickup),
    ("thump", 0.12, punch),
    ("impact", 0.18, block_break),
    ("click", 0.11, place),
)


def samples(duration: float, generator) -> list[int]:
    count = round(duration * SAMPLE_RATE)
    values = [generator(index / SAMPLE_RATE, index) for index in range(count)]
    peak = max(max(values), -min(values), 0.001)
    scale = 0.72 * 32767.0 / peak
    return [max(-32768, min(32767, round(value * scale))) for value in values]


def write_wav(path: Path, values: list[int]) -> None:
    with wave.open(str(path), "wb") as output:
        output.setnchannels(1)
        output.setsampwidth(2)
        output.setframerate(SAMPLE_RATE)
        output.writeframes(struct.pack(f"<{len(values)}h", *values))


def main() -> None:
    project = Path(__file__).resolve().parent.parent
    output_dir = project / "assets" / "audio" / "sfx"
    header = project / "assets" / "game_sfx.h"
    output_dir.mkdir(parents=True, exist_ok=True)
    header.parent.mkdir(parents=True, exist_ok=True)

    defines = [
        "/* Generated by tools/generate_sfx.py; do not edit. */",
        "#ifndef GAME_SFX_H",
        "#define GAME_SFX_H",
        "",
        f"#define SFX_SAMPLE_RATE {SAMPLE_RATE}",
    ]
    for name, duration, generator in EFFECTS:
        values = samples(duration, generator)
        write_wav(output_dir / f"{name}.wav", values)
        (output_dir / f"{name}.pcm.bin").write_bytes(
            struct.pack(f">{len(values)}h", *values)
        )
        macro = name.upper()
        defines.append(f"#define SFX_{macro}_SAMPLE_COUNT {len(values)}")
        defines.append(f"#define SFX_{macro}_DATA_BYTES {len(values) * 2}")

    defines.extend(("", "#endif /* GAME_SFX_H */", ""))
    header.write_text("\n".join(defines), encoding="ascii")
    print(f"Generated {len(EFFECTS)} effects in {output_dir}")


if __name__ == "__main__":
    main()
